#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : golang-github-fzipp-gocyclo
Version  : 6acd4345c835499920e8426c7e4e8d7a34f1bb83
Release  : 1
URL      : https://github.com/fzipp/gocyclo/archive/6acd4345c835499920e8426c7e4e8d7a34f1bb83.tar.gz
Source0  : https://github.com/fzipp/gocyclo/archive/6acd4345c835499920e8426c7e4e8d7a34f1bb83.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-3-Clause
BuildRequires : go

%description
Gocyclo calculates cyclomatic complexities of functions in Go source code.
The cyclomatic complexity of a function is calculated according to the
following rules:

%prep
%setup -q -n gocyclo-6acd4345c835499920e8426c7e4e8d7a34f1bb83

%build
export LANG=C

%install
gopath="/usr/lib/golang"
library_path=""
rm -rf %{buildroot}
install -d -p %{buildroot}${gopath}/src/${library_path}/
for file in $(find . -iname "*.go" -o -iname "*.h" -o -iname "*.c") ; do
     echo ${file}
     install -d -p %{buildroot}${gopath}/src/${library_path}/$(dirname $file)
     cp -pav $file %{buildroot}${gopath}/src/${library_path}/$file
done

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
gopath="/usr/lib/golang"
export GOPATH="%{buildroot}${gopath}"
go test -v -x

%files
%defattr(-,root,root,-)
/usr/lib/golang/src/gocyclo.go
